# Generated by Django 5.1.4 on 2025-01-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(choices=[('Aion', 'Aion'), ('Arc', 'Arc'), ('Asset', 'Asset')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_range', models.CharField(blank=True, choices=[('under-10000', 'Under ₹10,000'), ('10000-25000', '₹10,000 to ₹25,000'), ('25000-50000', '₹25,000 to ₹50,000')], max_length=20)),
                ('case_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20)),
                ('dial_color', models.CharField(choices=[('black', 'Black'), ('blue', 'Blue'), ('white', 'White')], max_length=20)),
                ('strap_color', models.CharField(choices=[('brown', 'Brown'), ('black', 'Black'), ('silver', 'Silver')], max_length=20)),
                ('dial_shape', models.CharField(choices=[('round', 'Round'), ('square', 'Square'), ('rectangular', 'Rectangular')], max_length=20)),
                ('movement', models.CharField(choices=[('quartz', 'Quartz'), ('automatic', 'Automatic'), ('mechanical', 'Mechanical')], max_length=20)),
                ('image', models.ImageField(upload_to='watches/')),
            ],
        ),
    ]
