# Generated by Django 5.1.4 on 2025-01-16 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_watch_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
