# Generated by Django 5.1.4 on 2025-01-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
