# Generated by Django 5.1.4 on 2025-01-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
