# Generated by Django 5.1.4 on 2025-03-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='watches',
            field=models.ManyToManyField(blank=True, to='app.watch'),
        ),
    ]
