# Generated by Django 5.1.4 on 2025-03-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cart_watches'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='quantity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
