# Generated by Django 5.1.4 on 2025-03-26 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='app.watch')),
            ],
        ),
    ]
