# Generated by Django 5.1.4 on 2025-03-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_watchdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_buy_now',
            field=models.BooleanField(default=False),
        ),
    ]
