# Generated by Django 5.1.4 on 2025-03-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_cart_is_buy_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_buy_now',
            field=models.BooleanField(default=False),
        ),
    ]
