# Generated by Django 5.1.4 on 2025-04-03 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='watches',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.cart'),
        ),
    ]
