# Generated by Django 5.1.4 on 2025-04-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_cart_watches_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='adjustable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='band_length',
            field=models.PositiveIntegerField(blank=True, help_text='Length in mm', null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='band_width',
            field=models.PositiveIntegerField(blank=True, help_text='Width in mm', null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='case_diameter',
            field=models.PositiveIntegerField(blank=True, help_text='Diameter in mm', null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='wrist_size',
            field=models.CharField(blank=True, choices=[('xs', 'Extra Small (5-6 inches)'), ('s', 'Small (6-6.5 inches)'), ('m', 'Medium (6.5-7 inches)'), ('l', 'Large (7-7.5 inches)'), ('xl', 'Extra Large (7.5+ inches)')], max_length=20, null=True),
        ),
    ]
