# Generated by Django 5.1.4 on 2025-05-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='model',
            field=models.CharField(choices=[('Seiko', 'Seiko'), ('Arc', 'Arc'), ('Asset', 'Asset')], max_length=20),
        ),
    ]
