# Generated by Django 5.1.4 on 2025-05-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_watch_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='model',
            field=models.CharField(choices=[('Aion', 'Aion'), ('Arc', 'Arc'), ('Asset', 'Asset')], max_length=20),
        ),
    ]
